---
hostname: R-2
interfaces :
  - name : loopback0
    description: For OSPF Router-ID
    ip_address : 2.2.2.2
  - name : GigabitEthernet0/1
    description : To Switch 2
    ip_address : 10.2.1.2
    netmask : 255.255.255.0
  - name : GigabitEthernet0/3
    description : To R3
    ip_address : 10.2.3.2
    netmask : 255.255.255.0
  - name : GigabitEthernet0/2
    description : To R1
    ip_address : 10.1.2.2
    netmask : 255.255.255.0
  - name : GigabitEthernet0/11
    description : Management
    nat : outside
    ip_address : 172.30.15.12
    netmask : 255.255.255.0
router_id: 2.2.2.2
nat : True
nat_interface : GigabitEthernet0/11
