---
hostname: SW-1
interfaces :
  - name : GigabitEthernet3/3
    description : Management
    ip_address : 172.30.15.21
    netmask : 255.255.255.0
  - name : GigabitEthernet0/1
    description : To R-1
    mode : trunk
portchannels :
  - channel: 1
    description: To Sw-2
    members :
      - int : GigabitEthernet1/0
      - int : GigabitEthernet1/1
