---
hostname: SW-4
interfaces :
  - name: GigabitEthernet3/3
    description : Management
    ip_address : 172.30.15.24
    netmask : 255.255.255.0
  - name: GigabitEthernet0/1
    description : To R-4
portchannels :
  - channel: 1
    description: To Sw-3
    members :
      - int : GigabitEthernet1/0
      - int : GigabitEthernet1/1
routerport :
  - port : GigabitEthernet 0/1